name: ActionTest

on:
 push:
  branches: ["main"]
jobs:
 Hi:
  runs-on: windows-2022
  steps:
    - name: Say Hi
      run: echo "Hello World"
 Bye:
  runs-on: windows-2022
  steps:
    - name: Say Bye
      run: echo "Bye World"
    
 
