name: ActionTest

on:
  workflow_dispatch:
jobs:
 Hi:
  runs-on: windows-2022
  steps:
    - name: Say Hi
      run: echo "Hello World"
 Bye:
  needs: Hi
  runs-on: windows-2022
  steps:
    - name: Say Bye
      run: echo "Bye World"
    
 
